/**
 * docsIndexReportBody.ts — pure builder + parser for the docs-index sweep's
 * single judgement-required report issue.
 *
 * The sweep reconciles against an already-open tracker through a back-link
 * marker in the issue body plus a violation-set fingerprint — the shape
 * `promotionReconcileLink.ts` established for the promotion sweep. No I/O:
 * the sweep shell files/refreshes/closes the issue the caller resolves.
 */

import { createHash } from 'node:crypto';
import { formatViolation, type DocsIndexViolation } from './docsIndexHealth';
import { ADW_NONE_LABEL } from '../github/labelManager';

export const DOCS_INDEX_REPORT_MARKER = 'Reconciles: docs-index-health';

const MARKER_RE = /^Reconciles:\s*docs-index-health\s*$/m;
const FINGERPRINT_RE = /^Fingerprint:\s*([0-9a-f]+)\s*$/m;
const FINGERPRINT_LENGTH = 12;

const VIOLATION_SECTION_HEADINGS: Record<DocsIndexViolation['kind'], string> = {
  overlap: 'Overlapping Owns: globs',
  'orphan-doc': 'Orphan docs',
  'duplicate-entry': 'Duplicate entries',
  'non-canonical': 'Non-canonical serialization',
  'count-out-of-band': 'Entry count out of band',
};

/** Section display order — judgement calls that name a pair first, then the singular findings. */
const VIOLATION_SECTION_ORDER: readonly DocsIndexViolation['kind'][] = [
  'overlap',
  'orphan-doc',
  'duplicate-entry',
  'non-canonical',
  'count-out-of-band',
];

const RESOLUTION_RULE =
  'Resolution rule: the module doc keeps its package globs; the feature doc loses the overlapping glob; a feature-vs-feature overlap goes to the newest doc.';

// ---------------------------------------------------------------------------
// Fingerprint
// ---------------------------------------------------------------------------

/** Order-independent: sorts the formatted violation lines before hashing, so reordering the same violation set never changes the fingerprint. */
export function docsIndexViolationFingerprint(violations: readonly DocsIndexViolation[]): string {
  const lines = violations.map(formatViolation).sort();
  return createHash('sha1').update(lines.join('\n')).digest('hex').slice(0, FINGERPRINT_LENGTH);
}

// ---------------------------------------------------------------------------
// Issue body builder
// ---------------------------------------------------------------------------

export interface BuildDocsIndexReportIssueInput {
  readonly violations: readonly DocsIndexViolation[];
  readonly indexPath: string;
  readonly defaultBranch: string;
}

export interface DocsIndexReportIssueSpec {
  readonly title: string;
  readonly body: string;
  readonly labels: readonly string[];
}

function violationSection(kind: DocsIndexViolation['kind'], violations: readonly DocsIndexViolation[]): string[] {
  const matching = violations.filter((v) => v.kind === kind);
  if (matching.length === 0) return [];
  return [`## ${VIOLATION_SECTION_HEADINGS[kind]}`, '', ...matching.map((v) => `- ${formatViolation(v)}`), ''];
}

/**
 * Builds the `{title, body, labels}` spec for the docs-index sweep's single
 * report issue. Carries `hitl` (human decision required) and `adw:none` (the
 * cron's auto-pickup must not hand a judgement call to an agent — a human
 * relabels to delegate once the resolution is decided).
 */
export function buildDocsIndexReportIssue(input: BuildDocsIndexReportIssueInput): DocsIndexReportIssueSpec {
  const { violations, indexPath, defaultBranch } = input;
  const title = `\`docs-index-health\`: ${violations.length} violation(s) in ${indexPath}`;
  const fingerprint = docsIndexViolationFingerprint(violations);

  const body = [
    DOCS_INDEX_REPORT_MARKER,
    `Fingerprint: ${fingerprint}`,
    '',
    `The docs-index health sweep found ${violations.length} violation(s) in \`${indexPath}\` on \`${defaultBranch}\` that need a human decision.`,
    '',
    ...VIOLATION_SECTION_ORDER.flatMap((kind) => violationSection(kind, violations)),
    RESOLUTION_RULE,
    '',
    '<!-- This body is regenerated by the docs-index sweep whenever the violation set changes (see the Fingerprint line above). -->',
    '',
    'To delegate resolution to an ADW agent, remove the `adw:none` label and add `adw:chore`.',
  ].join('\n');

  return { title, body, labels: ['hitl', ADW_NONE_LABEL] };
}

// ---------------------------------------------------------------------------
// Marker parsing + reconcile
// ---------------------------------------------------------------------------

export interface DocsIndexReportMarker {
  readonly fingerprint: string;
}

/** Extracts the back-link marker + fingerprint from an issue body, or null when the marker is absent. */
export function parseDocsIndexReportMarker(body: string): DocsIndexReportMarker | null {
  if (!MARKER_RE.test(body)) return null;
  const match = FINGERPRINT_RE.exec(body);
  return match ? { fingerprint: match[1] } : null;
}

export interface DocsIndexReportIssueRef {
  readonly number: number;
  readonly body: string;
  /** 'OPEN' | 'CLOSED' (uppercase; compared case-insensitively). Absent ⇒ treated as open. */
  readonly state?: string;
}

function issueIsOpen(ref: DocsIndexReportIssueRef): boolean {
  return ref.state === undefined || ref.state.toUpperCase() === 'OPEN';
}

/** The lowest-numbered OPEN issue carrying the back-link marker, or null when none is open — mirrors `reconcilePromotionLink`. */
export function findOpenDocsIndexReport(issues: readonly DocsIndexReportIssueRef[]): DocsIndexReportIssueRef | null {
  const candidates = issues.filter((i) => issueIsOpen(i) && parseDocsIndexReportMarker(i.body) !== null);
  if (candidates.length === 0) return null;
  return candidates.reduce((lowest, cur) => (cur.number < lowest.number ? cur : lowest));
}
