/**
 * Drives the real `executeUpgrade` against a throwaway git repository. Every dependency that
 * would reach a forge or the git boundary is wired here; a dependency the scenario does not
 * wire throws on first use instead of silently succeeding.
 */

import { Before, After, Given, When, Then } from '@cucumber/cucumber';
import assert from 'assert';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { execFileSync, execSync } from 'child_process';
import { fileURLToPath } from 'node:url';

import { Platform } from '@paysdoc/devplatform';
import type { BoundProviders, RepoIdentifier } from '@paysdoc/devplatform';
import { commitOps } from '@paysdoc/devplatform/git';
import type { GitContext } from '@paysdoc/devplatform/git';

import { executeUpgrade, buildDefaultUpgradeDeps } from '../../../adws/adwUpgrade.tsx';
import type { RunInitCommandParams, UpgradeDeps, UpgradeRunResult } from '../../../adws/adwUpgrade.tsx';
import { parseAdwYml } from '../../../adws/core/adwYmlConfig.ts';
import { REQUIRED_ADW_FILES } from '../../../adws/phases/worktreeSetup.ts';

import { disposeToolchain, syncProjectUnderToolchain } from './feature-992-standins.ts';

const FRAMEWORK_REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const REPO_ID: RepoIdentifier = { owner: 'adw-fixture', repo: 'target-931', platform: Platform.GitHub };
const UPGRADE_ISSUE_NUMBER = 931;
const UPGRADE_ADW_ID = 'adw931-upgrade';
const OLD_FRAMEWORK_HASH = '0'.repeat(64);
const VOCABULARY_PATH = 'features/regression/vocabulary.md';
const AGENT_OUTPUT_PATHS: readonly string[] = [
  ...REQUIRED_ADW_FILES.map((file) => `.adw/${file}`),
  VOCABULARY_PATH,
];

const UPGRADE_SCENARIOS = '@adw-931 or @adw-991 or @adw-992';
const DEFAULT_MANIFEST = { file: 'package.json', content: '{ "name": "adw-931-target", "version": "0.0.0" }\n' };

interface AdwInitAgent {
  command: string;
  leavesUntouched: string | null;
  /** What the stub writes as ".adw/project.md"; null leaves it the text every regenerated file gets. */
  projectMd: string | null;
  /** Further files the stub writes, by path from the repository's root, after the complete configuration. */
  extraFiles: Readonly<Record<string, string>>;
}

export interface World931 {
  repoDir: string;
  tempDirs: string[];
  seededAdwYml: string | null;
  agent: AdwInitAgent | null;
  headBefore: string;
  result: UpgradeRunResult | null;
  issueComments: string[];
}

const w: World931 = {
  repoDir: '',
  tempDirs: [],
  seededAdwYml: null,
  agent: null,
  headBefore: '',
  result: null,
  issueComments: [],
};

function resetWorld(): void {
  w.repoDir = '';
  w.tempDirs = [];
  w.seededAdwYml = null;
  w.agent = null;
  w.headBefore = '';
  w.result = null;
  w.issueComments = [];
}

Before({ tags: UPGRADE_SCENARIOS }, function () {
  resetWorld();
});

After({ tags: UPGRADE_SCENARIOS }, function () {
  for (const dir of w.tempDirs) fs.rmSync(dir, { recursive: true, force: true });
  disposeToolchain();
  resetWorld();
});

export function git(cwd: string, ...args: string[]): string {
  return execFileSync('git', args, { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] });
}

function runShell(command: string, cwd: string): string {
  return execSync(command, { cwd, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] });
}

export function commitAll(dir: string, message: string): void {
  git(dir, 'add', '-A');
  git(dir, 'commit', '-q', '-m', message);
}

function makeTempDir(prefix: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  w.tempDirs.push(dir);
  return dir;
}

export function createTargetRepo(initialisedByOlderFramework: boolean, manifest: { file: string; content: string } = DEFAULT_MANIFEST): void {
  const dir = makeTempDir('adw-931-target-');
  git(dir, 'init', '-q', '-b', 'main');
  git(dir, 'config', 'user.email', 'adw-931@test.dev');
  git(dir, 'config', 'user.name', 'ADW 931 Test');
  git(dir, 'config', 'commit.gpgsign', 'false');
  fs.writeFileSync(path.join(dir, manifest.file), manifest.content);
  fs.writeFileSync(path.join(dir, 'README.md'), '# Target repository\n');
  if (initialisedByOlderFramework) {
    fs.mkdirSync(path.join(dir, '.adw'), { recursive: true });
    for (const file of REQUIRED_ADW_FILES) {
      fs.writeFileSync(path.join(dir, '.adw', file), `# ${file} from an older framework version\n`);
    }
    fs.writeFileSync(path.join(dir, '.adw-version'), `${OLD_FRAMEWORK_HASH}\n`);
  }
  commitAll(dir, 'chore: initial target repository');
  w.repoDir = dir;
}

function boundaryNotWired<T extends object>(name: string): T {
  return new Proxy({}, {
    get(_target, prop) {
      throw new Error(`Scenario reached the unwired ${name} boundary: ${String(prop)}`);
    },
  }) as T;
}

function regeneratedContent(file: string): string {
  if (file === 'project.md' && w.agent?.projectMd) return w.agent.projectMd;
  return `# ${file} regenerated by the current framework version\n`;
}

async function runAdwInitStub(params: RunInitCommandParams): Promise<{ success: boolean }> {
  const adwDir = path.join(params.worktreePath, '.adw');
  fs.mkdirSync(adwDir, { recursive: true });
  for (const file of REQUIRED_ADW_FILES) {
    fs.writeFileSync(path.join(adwDir, file), regeneratedContent(file));
  }
  const vocabularyFile = path.join(params.worktreePath, VOCABULARY_PATH);
  fs.mkdirSync(path.dirname(vocabularyFile), { recursive: true });
  fs.writeFileSync(vocabularyFile, '# Regression vocabulary\n');
  for (const [relativePath, content] of Object.entries(w.agent?.extraFiles ?? {})) {
    const file = path.join(params.worktreePath, relativePath);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
  return { success: true };
}

function buildUpgradeDeps(): UpgradeDeps {
  const repoDir = w.repoDir;
  const logsDir = makeTempDir('adw-931-logs-');
  return {
    ...buildDefaultUpgradeDeps(boundaryNotWired<BoundProviders>('providers'), boundaryNotWired<GitContext>('git context')),
    ensureWorktree: () => repoDir,
    reconcileWorktreeToRemote: () => {},
    getDefaultBranch: () => 'main',
    findPRByBranch: () => null,
    runInitCommand: runAdwInitStub,
    copyInitCommandToWorktree: () => {},
    syncScenarioProject: syncProjectUnderToolchain,
    commitChanges: (message, cwd, opts) => commitOps.commitChanges(runShell, message, cwd, opts),
    pushBranch: () => {},
    createPullRequest: () => ({ url: `https://github.com/${REPO_ID.owner}/${REPO_ID.repo}/pull/1`, number: 1 }),
    commentOnIssue: (_issueNumber, body) => { w.issueComments.push(body); },
    ensureLogsDirectory: () => logsDir,
    mergePR: () => ({ success: true }),
    fetchIssueLabels: () => [],
    fetchIssueComments: () => [],
  };
}

function parseNameStatusLine(line: string): { status: string; file: string } {
  const [status, file] = line.split('\t');
  return { status, file };
}

function regenCommitEntries(): { status: string; file: string }[] {
  return git(w.repoDir, 'show', '--no-renames', '--name-status', '--format=', 'HEAD')
    .split('\n')
    .filter(Boolean)
    .map(parseNameStatusLine);
}

export function regenCommitFile(filePath: string): string {
  return git(w.repoDir, 'show', `HEAD:${filePath}`);
}

/** Configures the stubbed "/adw_init" agent, which writes `projectMd` as the repository's ".adw/project.md", and `extraFiles` besides. */
export function configureAdwInitAgent(command: string, projectMd: string, extraFiles: Readonly<Record<string, string>> = {}): void {
  w.agent = { command, leavesUntouched: null, projectMd, extraFiles };
}

/** What the scenario's upgrade has done so far, for the scenarios of later features that read it. */
export function upgradeWorld(): Readonly<World931> {
  return w;
}

function assertUnitTestSwitch(filePath: string, expected: boolean): void {
  assert.strictEqual(
    parseAdwYml(regenCommitFile(filePath)).unitTests,
    expected,
    `Expected ADW to read unitTests as ${expected} from the regen commit's "${filePath}"`,
  );
}

Given('a target repository never initialised by ADW', function () {
  createTargetRepo(false);
});

Given('a target repository initialised by an older framework version', function () {
  createTargetRepo(true);
});

Given("the target repository's default branch has no {string}", function (filePath: string) {
  assert.ok(w.repoDir, 'Expected a target repository to have been prepared first');
  const tracked = git(w.repoDir, 'ls-tree', '-r', '--name-only', 'main').split('\n');
  assert.ok(!tracked.includes(filePath), `Expected the default branch to have no "${filePath}"`);
});

Given("the target repository's default branch has this {string}:", function (filePath: string, content: string) {
  assert.ok(w.repoDir, 'Expected a target repository to have been prepared first');
  const file = path.join(w.repoDir, filePath);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  commitAll(w.repoDir, `chore: add ${filePath}`);
  w.seededAdwYml = content;
});

Given(
  'the {string} agent writes a complete ADW configuration and does not touch {string}',
  function (command: string, leavesUntouched: string) {
    assert.ok(
      !AGENT_OUTPUT_PATHS.includes(leavesUntouched),
      `The stubbed "${command}" agent writes "${leavesUntouched}", contradicting the scenario`,
    );
    w.agent = { command, leavesUntouched, projectMd: null, extraFiles: {} };
  },
);

export async function runFrameworkUpgrade(): Promise<void> {
  assert.ok(w.repoDir, 'Expected a target repository to have been prepared first');
  assert.ok(w.agent, 'Expected the /adw_init agent to have been configured first');
  w.headBefore = git(w.repoDir, 'rev-parse', 'HEAD').trim();
  w.result = await executeUpgrade(UPGRADE_ISSUE_NUMBER, UPGRADE_ADW_ID, REPO_ID, w.repoDir, FRAMEWORK_REPO_ROOT, buildUpgradeDeps());
}

When(
  "the framework upgrade regenerates the target repository's ADW configuration",
  { timeout: 60_000 },
  runFrameworkUpgrade,
);

Then('the upgrade commits the regenerated configuration', function () {
  assert.ok(w.result, 'Expected the framework upgrade to have run');
  assert.strictEqual(
    w.result.outcome,
    'completed',
    `Expected the upgrade to complete, got ${w.result.outcome}/${w.result.reason}. Comments posted: ${JSON.stringify(w.issueComments)}`,
  );
  assert.notStrictEqual(git(w.repoDir, 'rev-parse', 'HEAD').trim(), w.headBefore, 'Expected the upgrade to add a commit');
});

Then('the regen commit adds {string}', function (filePath: string) {
  const entries = regenCommitEntries();
  assert.ok(
    entries.some((entry) => entry.status === 'A' && entry.file === filePath),
    `Expected the regen commit to add "${filePath}", it changed: ${JSON.stringify(entries)}`,
  );
});

Then('the regen commit does not change {string}', function (filePath: string) {
  const entries = regenCommitEntries();
  assert.ok(
    !entries.some((entry) => entry.file === filePath),
    `Expected the regen commit not to change "${filePath}", it changed: ${JSON.stringify(entries)}`,
  );
  assert.ok(w.seededAdwYml !== null, 'Expected the scenario to have seeded the file on the default branch');
  assert.strictEqual(regenCommitFile(filePath), w.seededAdwYml);
});

Then("ADW reads the unit-test switch in the regen commit's {string} as enabled", function (filePath: string) {
  assertUnitTestSwitch(filePath, true);
});

Then("ADW reads the unit-test switch in the regen commit's {string} as disabled", function (filePath: string) {
  assertUnitTestSwitch(filePath, false);
});
