@adw-276
Feature: Wire proof data into structured issue comments

  Fix the data drop where scenario proof results are generated by reviewRetry.ts
  but never surface in GitHub issue comments. A Proof Comment Formatter module
  takes scenario proof results, verification results, review summary, and blocker/
  non-blocker issues, then produces structured markdown. The wiring layer in
  workflowCompletion.ts and workflowCommentsIssue.ts consumes this formatter output
  to post rich proof comments on the issue.

  Background:
    Given the ADW codebase is at the current working directory

  # ── 1. Proof Comment Formatter module exists ─────────────────────────────────

  @adw-276 @regression
  Scenario: Proof Comment Formatter module exists with a clean interface
    Given the proof comment formatter module exists
    Then it exports a function that accepts scenario proof results
    And it exports a function that accepts verification results
    And it exports a function that accepts review summary text
    And it exports a function that accepts blocker and non-blocker issues
    And it returns structured markdown as a string

  # ── 2. Passed review comment formatting ──────────────────────────────────────

  @adw-276 @regression
  Scenario: Formatter produces correct markdown for a passed review
    Given a passed review with summary "All checks passed successfully"
    And scenario proof results where "@review-proof" passed and "@adw-276" passed
    And verification results where type-check passed and lint passed
    And 2 non-blocker issues
    And 0 blocker issues
    When the proof comment formatter formats the review comment
    Then the output contains a review status header indicating "passed"
    And the output contains the review summary text
    And the output contains a scenario proof table with suite and status columns
    And the proof table shows "@review-proof" as passed
    And the proof table shows "@adw-276" as passed
    And the output contains a verification section showing type-check passed
    And the output contains a verification section showing lint passed
    And the output contains a collapsible non-blocker issues section
    And the output does not contain a blocker issues section

  @adw-276
  Scenario: Passed review comment includes scenario counts in proof table
    Given a passed review with scenario proof results
    And the "@review-proof" tag ran 5 scenarios with 5 passing
    And the "@adw-276" tag ran 3 scenarios with 3 passing
    When the proof comment formatter formats the review comment
    Then the proof table includes scenario counts for each suite

  @adw-276
  Scenario: Passed review comment omits non-blocker section when there are none
    Given a passed review with summary "Clean review"
    And scenario proof results where all tags passed
    And verification results where all checks passed
    And 0 non-blocker issues
    When the proof comment formatter formats the review comment
    Then the output does not contain a non-blocker issues section

  # ── 3. Failed review comment formatting ──────────────────────────────────────

  @adw-276 @regression
  Scenario: Formatter produces correct markdown for a failed review
    Given a failed review with summary "Blocker issues found"
    And scenario proof results where "@review-proof" passed and "@adw-276" failed
    And verification results where type-check passed and lint failed
    And 1 non-blocker issue
    And 3 blocker issues
    When the proof comment formatter formats the review comment
    Then the output contains a review status header indicating "failed"
    And the output contains the review summary text
    And the output contains a scenario proof table with suite and status columns
    And the proof table shows "@review-proof" as passed
    And the proof table shows "@adw-276" as failed
    And the output contains a verification section showing type-check passed
    And the output contains a verification section showing lint failed
    And the output contains a collapsible blocker issues section
    And the output contains a collapsible non-blocker issues section
    And the output contains a collapsible full scenario output section

  @adw-276
  Scenario: Failed review comment includes full scenario output in collapsible section
    Given a failed review with scenario proof output text
    And the scenario proof output contains multi-line test runner output
    When the proof comment formatter formats the review comment
    Then the output contains a "<details>" section for full scenario output
    And the details section contains the raw scenario proof output

  @adw-276
  Scenario: Failed review shows blocker issues with descriptions
    Given a failed review with 2 blocker issues each having a description
    When the proof comment formatter formats the review comment
    Then the collapsible blocker issues section lists each blocker with its description

  # ── 4. Collapsible sections ──────────────────────────────────────────────────

  @adw-276 @regression
  Scenario: Scenario output is in a collapsible details section
    Given a failed review with scenario proof output
    When the proof comment formatter formats the review comment
    Then the scenario output section uses a "<details>" HTML element
    And the "<details>" element has a "<summary>" describing the section
    And the section content is inside the details element

  @adw-276 @regression
  Scenario: Non-blocker issues are in a collapsible details section
    Given a review with 3 non-blocker issues
    When the proof comment formatter formats the review comment
    Then the non-blocker issues section uses a "<details>" HTML element
    And the "<details>" element has a "<summary>" describing the section
    And the section content lists all non-blocker issues

  @adw-276
  Scenario: Blocker issues are in a collapsible details section on failure
    Given a failed review with 2 blocker issues
    When the proof comment formatter formats the review comment
    Then the blocker issues section uses a "<details>" HTML element
    And the "<details>" element has a "<summary>" describing the section

  # ── 5. Skipped optional tags in proof table ──────────────────────────────────

  @adw-276
  Scenario: Proof table shows skipped optional tags appropriately
    Given scenario proof results where "@adw-276" was skipped because no matching scenarios exist
    And the "@adw-276" tag is marked as optional
    When the proof comment formatter formats the review comment
    Then the proof table shows "@adw-276" as skipped
    And the skipped entry does not count as a failure

  # ── 6. Verification section formatting ───────────────────────────────────────

  @adw-276
  Scenario: Verification section shows supplementary check results
    Given verification results with type-check passed and lint failed
    When the proof comment formatter formats the verification section
    Then the output contains a verification table or list
    And each check shows its name, status, and severity

  @adw-276
  Scenario: Verification section omitted when no supplementary checks exist
    Given no verification results are provided
    When the proof comment formatter formats the review comment
    Then the output does not contain a verification section

  # ── 7. reviewRetry.ts passes proof data through ─────────────────────────────

  @adw-276 @regression
  Scenario: reviewRetry.ts returns scenarioProof in ReviewRetryResult
    Given the file "adws/agents/reviewRetry.ts" is read
    When the ReviewRetryResult interface is inspected
    Then it includes a "scenarioProof" field of type ScenarioProofResult
    And it includes an "allScreenshots" field
    And it includes an "allSummaries" field

  @adw-276
  Scenario: reviewRetry.ts populates scenarioProof from the final review iteration
    Given the file "adws/agents/reviewRetry.ts" is read
    When the runReviewWithRetry function is inspected
    Then scenarioProof is assigned from the scenario proof execution result
    And the scenarioProof value is included in the returned ReviewRetryResult

  # ── 8. workflowCompletion.ts consumes proof data ────────────────────────────

  @adw-276 @regression
  Scenario: workflowCompletion.ts extracts proof data from review result
    Given the file "adws/phases/workflowCompletion.ts" is read
    When the executeReviewPhase function is inspected
    Then it extracts "scenarioProof" from the ReviewRetryResult
    And it extracts "allScreenshots" from the ReviewRetryResult
    And it extracts "allSummaries" from the ReviewRetryResult

  @adw-276 @regression
  Scenario: workflowCompletion.ts passes proof data to the comment formatter
    Given the file "adws/phases/workflowCompletion.ts" is read
    When the review comment posting logic is inspected
    Then it passes scenarioProof to the proof comment formatter or comment context
    And it passes verification results to the proof comment formatter or comment context

  @adw-276
  Scenario: workflowCompletion.ts posts structured comment to the issue
    Given the file "adws/phases/workflowCompletion.ts" is read
    When the review phase completion logic is inspected
    Then it calls the issue comment posting function with the formatted proof comment

  # ── 9. workflowCommentsIssue.ts uses new comment format ─────────────────────

  @adw-276 @regression
  Scenario: workflowCommentsIssue.ts review_passed format uses proof comment formatter
    Given the file "adws/github/workflowCommentsIssue.ts" is read
    When the review passed comment formatting is inspected
    Then it uses the proof comment formatter to build the comment body
    And the comment includes the scenario proof table
    And the comment includes the verification section

  @adw-276 @regression
  Scenario: workflowCommentsIssue.ts review_failed format uses proof comment formatter
    Given the file "adws/github/workflowCommentsIssue.ts" is read
    When the review failed comment formatting is inspected
    Then it uses the proof comment formatter to build the comment body
    And the comment includes the blocker issues section
    And the comment includes the scenario proof table
    And the comment includes the full scenario output section

  @adw-276
  Scenario: workflowCommentsIssue.ts accepts proof data in its context parameter
    Given the file "adws/github/workflowCommentsIssue.ts" is read
    When the comment context type or parameter is inspected
    Then it accepts scenarioProof as an optional field
    And it accepts verification results as an optional field

  # ── 10. Unit tests for Proof Comment Formatter ──────────────────────────────

  @adw-276 @regression
  Scenario: Unit tests exist for the proof comment formatter
    Given the proof comment formatter unit test file exists
    Then there are tests for passed review formatting
    And there are tests for failed review formatting
    And there are tests for review with non-blocker issues
    And there are tests for review without non-blocker issues

  @adw-276
  Scenario: Unit tests cover passed review with all sections present
    Given the proof comment formatter unit test file exists
    Then there is a test verifying passed review includes status header, summary, proof table, and verification

  @adw-276
  Scenario: Unit tests cover failed review with blocker and scenario output sections
    Given the proof comment formatter unit test file exists
    Then there is a test verifying failed review includes blocker issues and full scenario output

  @adw-276
  Scenario: Unit tests cover collapsible details sections
    Given the proof comment formatter unit test file exists
    Then there is a test verifying non-blocker issues use a details element
    And there is a test verifying scenario output uses a details element
    And there is a test verifying blocker issues use a details element on failure

  # ── 11. TypeScript integrity ─────────────────────────────────────────────────

  @adw-276 @regression
  Scenario: TypeScript type-check passes after all changes for issue 276
    Given the ADW codebase has been modified for issue 276
    When "bunx tsc --noEmit" and "bunx tsc --noEmit -p adws/tsconfig.json" are run
    Then both type-check commands exit with code 0
